<a href="https://colab.research.google.com/github/krishna324-art/Practice_Notebooks/blob/main/NumpyPractice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
def Printname(name,age,weight,Marks):
  print(f"The Datatype of age is{type(age)}")
  print(f"The Datatype of weight is{type(weight)}")
  print(f"The Datatype of name is{type(name)}")
  print(f"The Datatype of Marks is{type(Marks)}")
  return f"your name is {name},age is {age},weight is {weight}kg and your marks are {Marks}"
result=Printname("krishna Patel",21,62,[45,65,78])
print(result)

The Datatype of age is<class 'int'>
The Datatype of weight is<class 'int'>
The Datatype of name is<class 'str'>
The Datatype of Marks is<class 'list'>
your name is krishna Patel,age is 21,weight is 62kg and your marks are [45, 65, 78]


In [8]:
def Even_numbers(n):
 for i in range(n):
    if (i+1)%2==0:
     print(i+1)
Even_numbers(50)


2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50


In [9]:
#inefficient way for matrix multiplication
x=[1,2,3]
y=[4,5,6]
sum=0
for i in range(len(x)):
  sum=sum+x[i]*y[i]
print("the sum is",sum)

the sum is 32


In [25]:
import numpy as np
a=np.array([1,2,3])#1Darray
b=np.array([4,5,6])
c=np.array([[1,2,3],[4,5,10]])#2Darray

In [34]:
#broadcasting
a=a*2
print(a)

np.log10(c)
print(c[1][1])

[128 256 384]
5


In [29]:
np.sqrt(c)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 3.16227766]])

In [46]:
#reshaping and aggreagatioc
d=np.array([1,2,3,4,5,6])
d=np.reshape(d,(2,3))
s=np.reshape(d,(3,2))
print(s)
print(d)


[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]


In [51]:
k=np.array([[1,2,3],[4,5,6]])
print(np.sum(k,axis=0))
print(np.sum(k,axis=1))
print(np.mean(k,axis=0))

[5 7 9]
[ 6 15]
[2.5 3.5 4.5]


In [57]:
import numpy as np
import time
#size of array
N=100000
list1=list(range(N))
list2=list(range(N))
start=time.time()
result=[list1[i]*list2[i] for i in range(N)]
end=time.time()
print("python list time:",round(end-start,5),"seconds")
#using numpy
array1=np.arange(N)
array2=np.arange(N)
start=time.time()
result=array1*array2
end=time.time()
print("numpy time:",round(end-start,5),"seconds")

python list time: 0.0138 seconds
numpy time: 0.00215 seconds


In [56]:
import random
n=5
a=[]
for i in range(n):
  a.append([0]*n)
for i in range(n):
  for j in range(n):
    a[i][j]=random.random()
print(a)

[[0.09277234830124403, 0.9730727082278481, 0.24724556781040463, 0.41181631631354665, 0.2723573586107877], [0.07509118625989608, 0.8123090435106043, 0.4807448485118919, 0.21630855534856286, 0.9046930873485709], [0.46760297856534516, 0.06620700269585844, 0.899388843992095, 0.04673676256488202, 0.894982996676304], [0.17297268128227794, 0.1367526624313007, 0.17900359257861964, 0.7908780422129431, 0.305054021722693], [0.023858143382513464, 0.6017667001612207, 0.1588986205263897, 0.4191538901489883, 0.7317143880520852]]


In [79]:
A=np.array([[20,79,54],[45,65,89],[23,100,71],[88,55,90],[30,20,70]])
print(A)
meanscore=np.mean(A,axis=1)
print(meanscore)
subject_topscore=np.max(A,axis=0)
print(subject_topscore)
print("subject topper",np.argmax(A,axis=0))

print("overall topper is studnet ",np.argmax(np.sum(A,axis=1))+1)

[[ 20  79  54]
 [ 45  65  89]
 [ 23 100  71]
 [ 88  55  90]
 [ 30  20  70]]
[51.         66.33333333 64.66666667 77.66666667 40.        ]
[ 88 100  90]
subject topper [3 2 3]
overall topper is studnet  4
